apiVersion: v1

kind: Pod

metadata:
  name: web1
  labels:
    app: web

spec:
  containers:
    - name: front1
      image: httpd:latest
      ports:
        - containerPort: 80

    - name: back1
      image: centos:latest
      command: ["/bin/sh"]
      args: [ "-c", "while true; do echo Hello; sleep 10; done" ]
