apiVersion: v1

kind: Pod

metadata:
  name: web2
  labels:
    app: web2

spec:
  containers:
    - name: front2
      image: nginx:latest
      ports:
        - containerPort: 80

---
apiVersion: v1

kind: Service

metadata:
  name: service2

spec:
  type: NodePort
  selector:
    app: web2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
